name: Docker Image CI

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:

  build-code-debug:

    runs-on: ubuntu-latest

    steps:
    
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Update and Install dependencies
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y libboost-all-dev cmake

    - name: Build code in debug
      run: |
        cmake -S . -B Debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=Debug/install
        cmake --build Debug -j4
        cmake --build Debug -j4 -t run_unit_tests
        cmake --build Debug -j4 -t install

  build-code-release:

    runs-on: ubuntu-latest

    steps:
    
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Update and Install dependencies
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo apt-get install -y libboost-all-dev cmake

    - name: Build code in release
      run: |
        cmake -S . -B Release -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=Release/install
        cmake --build Release -j4 
        cmake --build Release -j4 -t run_unit_tests
        cmake --build Release -j4 -t install

  build-docker-image:

    runs-on: ubuntu-latest
    needs: [build-code-release, build-code-debug]

    steps:
    
    - name: Code checkout
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -f Dockerfile -t dummy-cpp:latest .

    - name: Test Run
      run: docker run -v $(pwd)/data:/app/data dummy-cpp:latest
